name: lexenv
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - cudatoolkit=10.2.89
  - freetype=2.10.2
  - intel-openmp=2020.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.1.1
  - python=3.7.7
  - pytorch=1.5.1
  - readline=8.0
  - setuptools=47.3.0
  - six=1.15.0
  - sqlite=3.32.2
  - tk=8.6.10
  - torchvision=0.6.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attrs==19.3.0
    - chardet==3.0.4
    - click==7.1.2
    - coloredlogs==14.0
    - discord-py==1.3.3
    - filelock==3.0.12
    - future==0.18.2
    - humanfriendly==8.2
    - idna==2.9
    - joblib==0.15.1
    - multidict==4.7.6
    - numpy==1.18.5
    - packaging==20.4
    - protobuf==3.12.2
    - pydantic==1.5.1
    - pyparsing==2.4.7
    - regex==2020.6.8
    - requests==2.24.0
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - stanza==1.0.1
    - tokenizers==0.7.0
    - tqdm==4.46.1
    - transformers==2.11.0
    - urllib3==1.25.9
    - websockets==8.1
    - yarl==1.4.2
